server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # lb:// = Eureka에서 서비스 이름으로 인스턴스를 찾아 로드밸런싱
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
